# Travis-CI config

language: node_js
node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn build

# Deploy
after_script:
  - cd ./dist
  - git init
  - git config user.name "ntnyq"
  - git config user.email "ntnyq13@gmail.com"
  - git add .
  - git commit -m ":rocket:Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/ntnyq/vue-animation.git
