/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./components/atomic/ActionButton.vue')['default']
    BlueCircle: typeof import('./components/BlueCircle.vue')['default']
    DarkToggle: typeof import('./components/atomic/DarkToggle.vue')['default']
    IconButton: typeof import('./components/atomic/IconButton.vue')['default']
    LsBox: typeof import('./components/LsBox.vue')['default']
    LsSection: typeof import('./components/LsSection.vue')['default']
    RedCircle: typeof import('./components/RedCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleButton: typeof import('./components/atomic/SimpleButton.vue')['default']
  }
}
