/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlueCircle: typeof import('./components/BlueCircle.vue')['default']
    LsBox: typeof import('./components/LsBox.vue')['default']
    LsSection: typeof import('./components/LsSection.vue')['default']
    RedCircle: typeof import('./components/RedCircle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
