/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/anime': RouteRecordInfo<'/anime', '/anime', Record<never, never>, Record<never, never>>,
    '/basic': RouteRecordInfo<'/basic', '/basic', Record<never, never>, Record<never, never>>,
    '/hook': RouteRecordInfo<'/hook', '/hook', Record<never, never>, Record<never, never>>,
    '/list': RouteRecordInfo<'/list', '/list', Record<never, never>, Record<never, never>>,
    '/multi': RouteRecordInfo<'/multi', '/multi', Record<never, never>, Record<never, never>>,
    '/router': RouteRecordInfo<'/router', '/router', Record<never, never>, Record<never, never>>,
  }
}
